name: store-local

services:

  postgres:
    container_name: store-db
    image: postgres:16.4
    restart: unless-stopped
    ports:
      - "${STORE_DB_PORT:-5432}:5432"
    environment:
      - CREATE_DATABASES=keycloak,store-admin,store-products
      - POSTGRES_USER=${STORE_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${STORE_DB_PASSWORD:-secret}
    command: postgres -c max_prepared_transactions=100
    volumes:
      - store_pgdata:/var/lib/postgresql/data
      - ./.env/postgres/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${STORE_DB_USER:-postgres}", "-d", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - store-network

  pgadmin:
    container_name: store-pgadmin
    image: dpage/pgadmin4:8.11.0
    restart: unless-stopped
    ports:
      - "${STORE_PGADMIN_PORT:-5433}:80"
    volumes:
      - store_pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${STORE_PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${STORE_PGADMIN_PASSWORD:-12345}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${STORE_PGADMIN_PORT:-5433}/misc/ping || exit -1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - store-network

  keycloak:
    container_name: store-keycloak
    image: quay.io/keycloak/keycloak:26.0.7
    restart: unless-stopped
    command: "-v start-dev --import-realm"
    ports:
      - "${STORE_KEYCLOAK_PORT:-8082}:9080"
    volumes:
      - store_keycloak:/opt/keycloak/data/import
#      - ./.env/keycloak/import:/opt/keycloak/data/import
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://store-db:${STORE_DB_PORT:-5432}/keycloak
      KC_DB_USERNAME: ${STORE_DB_USER:-postgres}
      KC_DB_PASSWORD: ${STORE_DB_PASSWORD:-secret}

      KC_HTTP_PORT: 9080
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: info
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [ "CMD-SHELL", "{ exec 3<>/dev/tcp/localhost/9080 && echo -e \"GET /health/ready HTTP/1.1\nhost: localhost:9080\n\" >&3 && timeout --preserve-status 1 cat <&3 | grep -m 1 -q 'status.*UP'; }" ]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5
    networks:
      - store-network

volumes:
  store_pgdata:
  store_pgadmin_data:
  store_keycloak:

networks:
  store-network:
    driver: bridge