server:
  port: ${STORE_ADMIN_PORT:8080}

spring:
  application:
    name: store-admin
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  mvc:
    log-request-details: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:${STORE_KEYCLOAK_PORT:8082}/realms/store
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: admin-app
            client-secret: PUZuiooo0d4vI4K1vUNwrw0o3IOqT7Qo
            scope:
              - openid
              - view_products
              - edit_products
              - microprofile-jwt

store:
  services:
    products:
      uri: http://localhost:${STORE_PRODUCTS_PORT:8081}
      registration-id: keycloak

logging:
  file:
    path: ./.logs/store-admin
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.web.cors: INFO
    org.apache.catalina.filters.RequestDumperFilter: INFO
    org.springframework.boot.autoconfigure: INFO
